### ISSUE TITLE
Doesn't support new version

### ISSUE THREAD

**Issue by Brncray** [DashCruft/Discord.JS-meme#23]
I dunno how to add the intents

**Comment by DashCruft** [comment]
So this is a request to upgrade to discord.js v13?

also fyi, intents r in depth in here:
https://discordjs.guide/popular-topics/intents.html#privileged-intents

**Comment by DashCruft** [comment]
Hey @Brncray,

I just updated this repo to the latest version of DJS (v13). You can also see how I passed all intents in my `index.js`
