### ISSUE TITLE
images does not load: Gif or video comes and bugs!

### ISSUE THREAD

**Issue by sebastianjnuwu** [DashCruft/Discord.JS-meme#25]
new bug try to fix it please! thank you!

**Comment by DashCruft** [comment]
I'll look into it. Thanks for the report.

**Comment by sebastianjnuwu** [comment]
ok the main bug is that videos or GIF comes and ends up bugging mainly video if there was a way to filter only the images I think this big one would have an end!

**Comment by DashCruft** [comment]
I just checked some gifs with the command.
Everything seems to be working and checking out fine on my end.

**Comment by sebastianjnuwu** [comment]
Ok
