### ISSUE TITLE
Bot Isn't Working

### ISSUE THREAD

**Issue by CrystalPheanix** [DashCruft/Discord.JS-meme#27]
Hey,The Bot isnt working when i open it on replit and input a secret (the token of my bot) and click on run i get it this issue

 npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-06-11T14_52_55_432Z-debug.log
exit status 1

Please help me

**Comment by DashCruft** [comment]
As @NotZer0Two mentioned, you are trying to run node through npm which is not possible because it's not defined in package.json.

Therefore, please run it by `node .` or node index.js`

Closing this issue.
